version: "3"

tasks:
  generate-proto:
    aliases: [gen-proto]
    desc: "Generate code from proto files"
    cmds:
      - protoc
        -I api/proto
        -I ${GOPATH}/src/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis
        --go_out=./api/gen
        --go_opt=paths=source_relative
        --go-grpc_out=./api/gen
        --go-grpc_opt=paths=source_relative
        --grpc-gateway_out=./api/gen
        --grpc-gateway_opt=paths=source_relative
        --validate_out=lang=go:./api/gen
        --validate_opt=paths=source_relative
        --openapiv2_out=./api/gen
        api/proto/*.proto

  install-deps-proto:
    aliases: [deps-proto]
    desc: "Install required dependencies for code generation"
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
      - go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest
      - go install github.com/envoyproxy/protoc-gen-validate@latest

  dockerfile-grpc:
    cmds:
      - docker build -f deployments/docker/grpc-server/Dockerfile -t todo-grpc-server .