# See: https://taskfile.dev/api/
# Use: task generate

version: "3"

tasks:
  generate:
    aliases: [gen]
    desc: "Generate code from proto files"
    cmds:
      - protoc
        -I proto
        --go_out=.
        --go_opt=paths=source_relative
        --go-grpc_out=.
        --go-grpc_opt=paths=source_relative
        --validate_out=lang=go:.
        --validate_opt=paths=source_relative
        proto/todo/*.proto