CREATE TABLE IF NOT EXISTS status (
    id SERIAL PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id SERIAL PRIMARY KEY,
    title VARCHAR(31) NOT NULL,
    description VARCHAR(255) NOT NULL,
    status_id INT REFERENCES status(id) ON DELETE RESTRICT,
    created_at TIMESTAMP DEFAULT NOW()
);