global:
  scrape_interval: 3s

scrape_configs:
  - job_name: 'grpc-service'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']